/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.*;
import java.util.*;
import server.ServerApp;
import javax.swing.table.DefaultTableModel;

public class ServerDashboard extends javax.swing.JFrame {
    
    
    public void forceUpdate() {
    // This method is called from ClientHandler when a vote is received
    updateDashboardData();
    }

private void updateDashboardData() {
    ArrayList<model.Voter> voterList = server.ServerApp.ballot.getVotersFromFile();
    
    // 1. Update "VOTING ATTEMPT" - shows TOTAL connection attempts (never decreases)
    textFieldConnectedClients.setText(String.valueOf(server.VotingServer.totalAttempts));
    
    // 2. Update "VOTE CAST" - shows total votes recorded
    textFieldTotalVotes.setText(String.valueOf(voterList.size()));
    
    // 3. Refresh Table
    DefaultTableModel model = (DefaultTableModel) TableClients.getModel();
    model.setRowCount(0);
    
    for (model.Voter v : voterList) {
        // Use the SAVED timestamp from the file
        String timeToDisplay = v.getSubmissionTime();
        
        // Fallback if timestamp is missing
        if (timeToDisplay == null || timeToDisplay.isEmpty() || timeToDisplay.equals("---")) {
            timeToDisplay = "--:--:--";
        }
        
        model.addRow(new Object[]{
            timeToDisplay,    // Column 0: Time (from file)
            v.getName(),      // Column 1: Name
            v.getId(),        // Column 2: ID
            "Voted"           // Column 3: Status
        });
    }
}
// REPLACE your existing startLiveUpdates() method with this:


    /**
     * Creates new form ServerDashboard
     */
    public ServerDashboard() {
       initComponents(); // NetBeans generated code
    
           server.ServerApp.dashboardInstance = this;

    // 1. Start the Server logic in a background thread
    new Thread(() -> {
        try {
            server.VotingServer vServer = new server.VotingServer(6000);
            vServer.startServer();
        } catch (Exception e) {
            System.err.println("Server Error: " + e.getMessage());
        }
    }).start();

    // 2. Set Network Info
    updateNetworkInfo();

    // 3. Update Status to ACTIVE
    textFieldStatus.setText("ACTIVE");
    textFieldStatus.setForeground(new java.awt.Color(114, 189, 53));

    // 4. Initial Data Load
    updateDashboardData(); 
}

// NEW METHOD: This replaces the Timer

private void updateNetworkInfo() {
    textFieldPort.setText("6000");
    try {
        String localIP = java.net.InetAddress.getLocalHost().getHostAddress();
        textFieldIP.setText(localIP);
    } catch (java.net.UnknownHostException e) {
        textFieldIP.setText("127.0.0.1");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TableClients = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnStatistics = new javax.swing.JButton();
        textFieldConnectedClients = new javax.swing.JTextField();
        textFieldTotalVotes = new javax.swing.JTextField();
        textFieldStatus = new javax.swing.JTextField();
        textFieldPort = new javax.swing.JTextField();
        textFieldIP = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 850));
        setResizable(false);
        getContentPane().setLayout(null);

        TableClients.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TableClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Time", "Name", "ID", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableClients.setFocusable(false);
        TableClients.setRowSelectionAllowed(false);
        TableClients.setUpdateSelectionOnSort(false);
        jScrollPane2.setViewportView(TableClients);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(170, 510, 1120, 240);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("IP Address:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1086, 80, 94, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SERVER STATUS");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(760, 350, 140, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Port:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(930, 76, 43, 30);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("HISTORY");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(190, 450, 90, 25);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TOTAL VOTES");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(480, 350, 120, 20);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CONNECTED CLIENTS");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(180, 350, 190, 20);

        btnStatistics.setBorder(null);
        btnStatistics.setBorderPainted(false);
        btnStatistics.setContentAreaFilled(false);
        btnStatistics.setFocusable(false);
        btnStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticsActionPerformed(evt);
            }
        });
        getContentPane().add(btnStatistics);
        btnStatistics.setBounds(1010, 210, 300, 180);

        textFieldConnectedClients.setEditable(false);
        textFieldConnectedClients.setBackground(new java.awt.Color(255, 255, 255));
        textFieldConnectedClients.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        textFieldConnectedClients.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldConnectedClients.setText("0");
        textFieldConnectedClients.setBorder(null);
        textFieldConnectedClients.setFocusable(false);
        textFieldConnectedClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldConnectedClientsActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldConnectedClients);
        textFieldConnectedClients.setBounds(170, 230, 210, 100);

        textFieldTotalVotes.setEditable(false);
        textFieldTotalVotes.setBackground(new java.awt.Color(255, 255, 255));
        textFieldTotalVotes.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        textFieldTotalVotes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldTotalVotes.setText("0");
        textFieldTotalVotes.setBorder(null);
        textFieldTotalVotes.setFocusable(false);
        textFieldTotalVotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTotalVotesActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldTotalVotes);
        textFieldTotalVotes.setBounds(431, 230, 200, 100);

        textFieldStatus.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textFieldStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldStatus.setText("NOT ACTIVE");
        textFieldStatus.setBorder(null);
        textFieldStatus.setFocusable(false);
        textFieldStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldStatusActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldStatus);
        textFieldStatus.setBounds(700, 230, 260, 100);

        textFieldPort.setEditable(false);
        textFieldPort.setBackground(new java.awt.Color(255, 255, 255));
        textFieldPort.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textFieldPort.setText("0000");
        textFieldPort.setBorder(null);
        textFieldPort.setFocusable(false);
        textFieldPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPortActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldPort);
        textFieldPort.setBounds(940, 120, 120, 20);

        textFieldIP.setEditable(false);
        textFieldIP.setBackground(new java.awt.Color(255, 255, 255));
        textFieldIP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textFieldIP.setText("IP..");
        textFieldIP.setBorder(null);
        textFieldIP.setFocusable(false);
        textFieldIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIPActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldIP);
        textFieldIP.setBounds(1100, 120, 190, 20);

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setBorder(null);
        btnReset.setBorderPainted(false);
        btnReset.setContentAreaFilled(false);
        btnReset.setFocusable(false);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset);
        btnReset.setBounds(1260, 440, 50, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/BG/IVOTE-GUI.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1400, 850);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldStatusActionPerformed

    private void textFieldIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIPActionPerformed

    private void textFieldPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPortActionPerformed

    private void textFieldConnectedClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldConnectedClientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldConnectedClientsActionPerformed

    private void textFieldTotalVotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTotalVotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTotalVotesActionPerformed

    private void btnStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticsActionPerformed

                   // 1. Get the data
            Map<String, List<model.Candidate>> positions = server.ServerApp.ballot.getCandidates();
            Map<String, Integer> voteCounts = server.ServerApp.ballot.getResults();

            if (voteCounts.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No votes recorded yet!", "Statistics", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 2. Build the Styled Report
            StringBuilder report = new StringBuilder();
            report.append("==============================================\n");
            report.append("           OFFICIAL VOTING RESULTS            \n");
            report.append("==============================================\n\n");

            for (String pos : positions.keySet()) {
                report.append(pos.toUpperCase()).append("\n");
                report.append("----------------------------------------------\n");

                List<model.Candidate> candidates = positions.get(pos);
                for (model.Candidate c : candidates) {
                    int count = voteCounts.getOrDefault(c.getId(), 0);

                    // Design: [Name] ............. [Count] Votes
                    // %-25s = Left align name, 25 spaces
                    // %10s  = Right align votes
                    String name = c.getFullName();
                    String line = String.format("- %-25s %10d Votes\n", name, count);
                    report.append(line);
                }
                report.append("\n"); // Space between positions
            }
            report.append("==============================================");

            // 3. UI Design Styling
            javax.swing.JTextArea textArea = new javax.swing.JTextArea(report.toString());
            textArea.setEditable(false);

            // CRITICAL: Monospaced font makes the columns line up
            textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.BOLD, 14));
            textArea.setBackground(new java.awt.Color(240, 240, 240));
            textArea.setMargin(new java.awt.Insets(15, 15, 15, 15));

            javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
            scrollPane.setPreferredSize(new java.awt.Dimension(500, 600));
            scrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Live Tally"));

            JOptionPane.showMessageDialog(this, scrollPane, "Election Statistics", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnStatisticsActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Reset all data? This cannot be undone.");
        if (confirm == JOptionPane.YES_OPTION) {
        // Change '.db' to '.ballot'
        ServerApp.ballot.resetSystem(); 
        
        textFieldTotalVotes.setText("0");
        textFieldConnectedClients.setText("0");
        ((javax.swing.table.DefaultTableModel)TableClients.getModel()).setRowCount(0);
    }
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableClients;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStatistics;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField textFieldConnectedClients;
    private javax.swing.JTextField textFieldIP;
    private javax.swing.JTextField textFieldPort;
    private javax.swing.JTextField textFieldStatus;
    private javax.swing.JTextField textFieldTotalVotes;
    // End of variables declaration//GEN-END:variables
}
